from tasks import fetch_data_task
from tasks import process_data_task
from tasks import store_data_task
from predefined_task import pre_defined_task_list

class flowManager:

    def __init__(self, user_input):
        self.id = user_input['flow']['id']
        self.name = user_input['flow']['name']
        self.start_task = user_input['flow']['start_task']
        self.tasks = user_input['flow']['tasks']
        self.conditions = user_input['flow']['conditions']
        
    

    def getLinkedClassName(self, current_task):
        for task in pre_defined_task_list:
            if(task['name'] == current_task):
                return task['classname'] 
        
        return None

    
    def getNextTask(self, current_task):
        for condition in self.conditions:
            if(condition['source_task'] == current_task):
                return condition['target_task_success']
        
        return None



    def startSequentialTaskProcessing(self, user_id):
        # Cold start init
        input_data = None
        current_task = self.start_task

        current_task_classname = self.getLinkedClassName(current_task)
        total_task_executed = 0

        if(current_task_classname == None):
            raise Exception

        while(total_task_executed < len(self.tasks)):
            class_instance = current_task_classname()
            
            # execute the task and capture the output generated by current task
            input_data = class_instance.execute(input_data, user_id)

            total_task_executed = total_task_executed + 1
            if(total_task_executed == len(self.tasks)):
                break
            
            # get the next task in the operation
            current_task = self.getNextTask(current_task)

            if(current_task == None):
                raise Exception

            current_task_classname = self.getLinkedClassName(current_task)

            if(current_task_classname == None):
                raise Exception

        
        if(total_task_executed != len(self.tasks)):
            raise Exception

        
            